services:
  a01-db:
    container_name: a01-devs-db
    image: postgres:16-alpine3.18
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - target: 5432
        published: 5433
        protocol: tcp
        mode: host
    expose: 
      - 5433
  a01-backend:
    container_name: a01-devs-backend
    build:
      context: ./devs-backend
      dockerfile: Dockerfile
    image: a01-devs-backend
    restart: always
    ports:
      - 8091:8091
    depends_on:
      - a01-db
    environment:
      - DB_HOST=a01-db
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - SERVER_PORT=${SERVER_PORT}
      - SERVER_PATH=${SERVER_PATH}
  a01-frontend:
    container_name: a01-devs-frontend
    build:
      context: ./devs-react-app
      dockerfile: Dockerfile
      args:
        - REACT_APP_BASE_PATH=${REACT_APP_BASE_PATH}
    image: a01-devs-frontend
    restart: always
    ports:
      - 3001:80
    depends_on:
      - a01-backend