CREATE TABLE model_tags
(
    model_id BIGINT NOT NULL,
    tag_id   BIGINT NOT NULL,
    CONSTRAINT pk_model_tags PRIMARY KEY (model_id, tag_id)
);

CREATE TABLE models
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    source_file BYTEA,
    version     INTEGER,
    based       INTEGER,
    create_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    delete_date TIMESTAMP WITHOUT TIME ZONE,
    update_date TIMESTAMP WITHOUT TIME ZONE,
    description VARCHAR(255)                            NOT NULL,
    user_id     BIGINT,
    favorite    BOOLEAN,
    CONSTRAINT pk_models PRIMARY KEY (id)
);

CREATE TABLE models_history
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    source_file BYTEA,
    version     INTEGER,
    create_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    update_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    user_id     BIGINT,
    model_id    BIGINT,
    CONSTRAINT pk_models_history PRIMARY KEY (id)
);

CREATE TABLE schemas
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    source_file BYTEA,
    version     INTEGER,
    based       INTEGER,
    create_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    delete_date TIMESTAMP WITHOUT TIME ZONE,
    update_date TIMESTAMP WITHOUT TIME ZONE,
    description VARCHAR(255)                            NOT NULL,
    user_id     BIGINT,
    CONSTRAINT pk_schemas PRIMARY KEY (id)
);

CREATE TABLE schemas_history
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    source_file BYTEA,
    version     INTEGER,
    create_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    update_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    user_id     BIGINT,
    schema_id   BIGINT,
    CONSTRAINT pk_schemas_history PRIMARY KEY (id)
);

CREATE TABLE tags
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    user_id     BIGINT,
    create_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    delete_date TIMESTAMP WITHOUT TIME ZONE,
    update_date TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_tags PRIMARY KEY (id)
);

CREATE TABLE users
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name  VARCHAR(255),
    last_name   VARCHAR(255),
    username    VARCHAR(255)                            NOT NULL,
    email       VARCHAR(255)                            NOT NULL,
    password    VARCHAR(255)                            NOT NULL,
    create_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    delete_date TIMESTAMP WITHOUT TIME ZONE,
    update_date TIMESTAMP WITHOUT TIME ZONE,
    role        VARCHAR(255),
    university  VARCHAR(255)                            NOT NULL,
    country     VARCHAR(255),
    occupation  VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);

ALTER TABLE models_history
    ADD CONSTRAINT FK_MODELS_HISTORY_ON_MODEL FOREIGN KEY (model_id) REFERENCES models (id);

ALTER TABLE models_history
    ADD CONSTRAINT FK_MODELS_HISTORY_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE models
    ADD CONSTRAINT FK_MODELS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE schemas_history
    ADD CONSTRAINT FK_SCHEMAS_HISTORY_ON_SCHEMA FOREIGN KEY (schema_id) REFERENCES schemas (id);

ALTER TABLE schemas_history
    ADD CONSTRAINT FK_SCHEMAS_HISTORY_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE schemas
    ADD CONSTRAINT FK_SCHEMAS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE model_tags
    ADD CONSTRAINT fk_modtag_on_model FOREIGN KEY (model_id) REFERENCES models (id);

ALTER TABLE model_tags
    ADD CONSTRAINT fk_modtag_on_tag FOREIGN KEY (tag_id) REFERENCES tags (id);